# Doctrine configuration
doctrine:
    dbal:
        default_connection: default
        connections:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                mappings:
                    PdirMobileDeBundle: ~
