services:
  pdir.mobile_de.ad_service:
    class: Pdir\MobileDeBundle\Service\AdService
    arguments:
    - "@doctrine.orm.entity_manager"
    public: true

  pdir.mobile_de.ad_dc:
    class: Pdir\MobileDeBundle\DataContainer\AdDataContainer
    arguments:
    - "@doctrine.orm.default_entity_manager"
    - "@pdir.mobile_de.ad_service"
    public: true
