services:
  pdir.mobile_de.dca.ad:
    class: Pdir\MobileDeBundle\Dca\Ad
    arguments:
      - "@contao.framework"
      - "@security.token_storage"
      - "@session"
      - "doctrine.orm.entity_manager"
    public: true
